step1: run dataprocess.py -generate_cas True
some warning may reported in step1, plz ingore them.
step2; run main.py